### ISSUE TITLE
Readme.md - Rückfrage

### ISSUE THREAD

**Issue by hexabinaer** [sanduhrs/cmsgarden#2]
Site-install als Dev-User ausgeführt führt dazu, dass Drupal wieder nicht in den files-Folder schreiben kann. Müssten wir da nicht schreiben `sudo -u www-data --preserve-env drush si minimal`? @sanduhrs

**Comment by sanduhrs** [comment]
Das ist leider immer system abhaengig.
in meinem Setup heisst der Benutzer unter dem der Webserver laeuft z.B. nicht www-data, sondern http.

Aber ja das waere sicher eine Loesung.

Wenn der Benutzer in der Gruppe {www-data|http} ist, reicht auch ein `chmod -R 775`

**Comment by sanduhrs** [comment]
Alternativ chmod 777 web/site/default/files
